GET http://localhost:8000/api/entry/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NzI2Njc4NTksImlkIjoxfQ.hVqDEHNWIIQq-95_oRpM5_tzSK--oC46xVGpFVC50Mo